apiVersion: 3mor.io/v1alpha1
kind: Location
metadata:
  name: aux-components
  description: A collection of all OpenContext aux components
spec:
  targets:
    - ./aux-components/aux-component-orchard.yaml
    - ./aux-components/aux-component-blue-sky.yaml
    - ./aux-components/aux-component-dumpster.yaml
    - ./aux-components/aux-component-it-ops.yaml
    - ./aux-components/aux-component-infocard.yaml
