apiVersion: opencontext.com/v1alpha1
kind: Location
metadata:
  name: code-component-extras
  description: A collection of all OpenContext code component sidecars
spec:
  targets:
    - ./code-components/component-extras-orchard.yaml
    - ./code-components/component-extras-dumpster.yaml
    - ./code-components/component-extras-blue-sky.yaml
