apiVersion: opencontext.com/v1alpha1
kind: CodeComponent
metadata:
  name: greenhouse-dataset
  description: Greenhouse historical data
  title: Greenhouse data archive
spec:
  type: other
  otherType: dataset
  owner: [prod-squirrel]
  service: greenhouse
  uri: s3://greenhouse-dataset
  dependsOn: [code-component:greenhouse-data]
  lifecycle: experimental
  datacenter: [aws]
