apiVersion: opencontext.com/v1alpha1
kind: CodeComponentSidecar
metadata:
  name: dumpster-data-extras
spec:
  codecomponent: dumpster-data
  platform: dumpster-prod
  lifecycle: production
  isPageable: true
  oncall1: user:daniel
  oncall2: user:michael
---
apiVersion: opencontext.com/v1alpha1
kind: CodeComponentSidecar
metadata:
  name: dumpster-ui-extras
spec:
  codecomponent: dumpster-ui
  platform: dumpster-prod
  lifecycle: production
  priority: 1
  sla: 24x7
  isPageable: true
  oncall1: user:brit
  oncall2: user:billy
---
apiVersion: opencontext.com/v1alpha1
kind: CodeComponentSidecar
metadata:
  name: dumpster-map-extras
spec:
  codecomponent: dumpster-map
  platform: dumpster-prod
  lifecycle: production
  priority: 1
  sla: 24x7
  isPageable: true
  oncall1: user:brit
  oncall2: user:billy
---
apiVersion: opencontext.com/v1alpha1
kind: CodeComponentSidecar
metadata:
  name: d3-extras
spec:
  codecomponent: d3
  platform: dumpster-prod
  lifecycle: production
  priority: 1
  sla: 24x7
  isPageable: true
  oncall1: user:brit
  oncall2: user:billy
