apiVersion: opencontext.com/v1alpha1
kind: CodeComponent
metadata:
  name: retail-app
  description: Blue Sky / Retail web app
  title: Retail app
  tags:
    - typescript
  links:
    - url: https://github.com/scatter-ly/retail-app/issues
      title: Issues
      icon: github
    - url: https://github.com/scatter-ly/retail-app/pulls
      title: Pull Requests
      icon: github
    - url: https://github.com/scatter-ly/retail-app/releases
      title: Releases
      icon: github
    - url: https://github.com/scatter-ly/retail-app/deployments
      title: Deployments
      icon: github
  annotations:
    github.com/project-slug: 'scatter-ly/retail-app'
spec:
  type: repository
  owner: [prod-raccoon-oss, eng-raccoon-cloud]
  dependsOn: [code-component:wholesale-graphql]
  uri: https://github.com/scatter-ly/retail-app
  service: retail
  lifecycle: production
  priority: 2
  sla: 8x5
  languages:
    - Dockerfile
    - TypeScript
  workflowsEnabled: true
  snykEnabled: true
  datadogEnabled: true
  releases:
    - name: v0.1.1
      uri: https://github.com/scatter-ly/retail-app/releases/tag/v0.1.1
    - name: v0.1.0
      uri: https://github.com/scatter-ly/retail-app/releases/tag/v0.1.0
  vulnerabilityAlerts:
    - uri: https://github.com/scatter-ly/retail-app/security/dependabot/24
      updatedAt: 2023-04-05T17:59:34Z
      severity: critical
      summary: Prototype Pollution in minimist
      manifestPath: yarn.lock
      package: minimist
      versionRange: < 0.2.4
      patchedVersion: 0.2.4
    - uri: https://github.com/scatter-ly/retail-app/security/dependabot/23
      updatedAt: 2023-04-05T17:59:34Z
      severity: high
      summary: loader-utils is vulnerable to Regular Expression Denial of Service
        (ReDoS) via url variable
      manifestPath: yarn.lock
      package: loader-utils
      versionRange: ">= 2.0.0, < 2.0.4"
      patchedVersion: 2.0.4
    - uri: https://github.com/scatter-ly/retail-app/security/dependabot/22
      updatedAt: 2023-04-05T17:59:34Z
      severity: high
      summary: loader-utils is vulnerable to Regular Expression Denial of Service
        (ReDoS)
      manifestPath: yarn.lock
      package: loader-utils
      versionRange: ">= 2.0.0, < 2.0.4"
      patchedVersion: 2.0.4
    - uri: https://github.com/scatter-ly/retail-app/security/dependabot/21
      updatedAt: 2023-04-05T17:59:34Z
      severity: critical
      summary: Prototype pollution in webpack loader-utils
      manifestPath: yarn.lock
      package: loader-utils
      versionRange: < 1.4.1
      patchedVersion: 1.4.1
    - uri: https://github.com/scatter-ly/retail-app/security/dependabot/20
      updatedAt: 2023-04-05T17:59:34Z
      severity: critical
      summary: Prototype pollution in webpack loader-utils
      manifestPath: yarn.lock
      package: loader-utils
      versionRange: ">= 2.0.0, < 2.0.3"
      patchedVersion: 2.0.3
    - uri: https://github.com/scatter-ly/retail-app/security/dependabot/19
      updatedAt: 2023-04-05T17:59:34Z
      severity: high
      summary: minimatch ReDoS vulnerability
      manifestPath: yarn.lock
      package: minimatch
      versionRange: < 3.0.5
      patchedVersion: 3.0.5
    - uri: https://github.com/scatter-ly/retail-app/security/dependabot/18
      updatedAt: 2023-04-05T17:59:33Z
      severity: critical
      summary: Improper Neutralization of Special Elements used in a Command in
        Shell-quote
      manifestPath: yarn.lock
      package: shell-quote
      versionRange: <= 1.7.2
      patchedVersion: 1.7.3
    - uri: https://github.com/scatter-ly/retail-app/security/dependabot/17
      updatedAt: 2023-04-05T17:59:33Z
      severity: critical
      summary: ejs template injection vulnerability
      manifestPath: yarn.lock
      package: ejs
      versionRange: < 3.1.7
      patchedVersion: 3.1.7
    - uri: https://github.com/scatter-ly/retail-app/security/dependabot/16
      updatedAt: 2023-04-05T17:59:33Z
      severity: medium
      summary: Improper Verification of Cryptographic Signature in `node-forge`
      manifestPath: yarn.lock
      package: node-forge
      versionRange: < 1.3.0
      patchedVersion: 1.3.0
    - uri: https://github.com/scatter-ly/retail-app/security/dependabot/15
      updatedAt: 2023-04-05T17:59:33Z
      severity: high
      summary: Improper Verification of Cryptographic Signature in node-forge
      manifestPath: yarn.lock
      package: node-forge
      versionRange: < 1.3.0
      patchedVersion: 1.3.0
    - uri: https://github.com/scatter-ly/retail-app/security/dependabot/14
      updatedAt: 2023-04-05T17:59:33Z
      severity: high
      summary: Improper Verification of Cryptographic Signature in node-forge
      manifestPath: yarn.lock
      package: node-forge
      versionRange: < 1.3.0
      patchedVersion: 1.3.0
    - uri: https://github.com/scatter-ly/retail-app/security/dependabot/13
      updatedAt: 2023-04-05T17:59:33Z
      severity: high
      summary: Uncontrolled Resource Consumption in ansi-html
      manifestPath: yarn.lock
      package: ansi-html
      versionRange: < 0.0.8
      patchedVersion: 0.0.8
    - uri: https://github.com/scatter-ly/retail-app/security/dependabot/12
      updatedAt: 2023-04-05T17:59:32Z
      severity: medium
      summary: Open Redirect in node-forge
      manifestPath: yarn.lock
      package: node-forge
      versionRange: < 1.0.0
      patchedVersion: 1.0.0
    - uri: https://github.com/scatter-ly/retail-app/security/dependabot/11
      updatedAt: 2023-04-05T17:59:32Z
      severity: low
      summary: Prototype Pollution in node-forge debug API.
      manifestPath: yarn.lock
      package: node-forge
      versionRange: < 1.0.0
      patchedVersion: 1.0.0
    - uri: https://github.com/scatter-ly/retail-app/security/dependabot/10
      updatedAt: 2023-04-05T17:59:32Z
      severity: low
      summary: URL parsing in node-forge could lead to undesired behavior.
      manifestPath: yarn.lock
      package: node-forge
      versionRange: < 1.0.0
      patchedVersion: 1.0.0
    - uri: https://github.com/scatter-ly/retail-app/security/dependabot/9
      updatedAt: 2023-04-05T17:59:32Z
      severity: high
      summary: Inefficient Regular Expression Complexity in nth-check
      manifestPath: yarn.lock
      package: nth-check
      versionRange: < 2.0.1
      patchedVersion: 2.0.1
    - uri: https://github.com/scatter-ly/retail-app/security/dependabot/8
      updatedAt: 2023-04-05T17:59:32Z
      severity: high
      summary: Prototype Pollution in immer
      manifestPath: yarn.lock
      package: immer
      versionRange: < 9.0.6
      patchedVersion: 9.0.6
    - uri: https://github.com/scatter-ly/retail-app/security/dependabot/7
      updatedAt: 2023-04-05T17:59:32Z
      severity: critical
      summary: Prototype Pollution in immer
      manifestPath: yarn.lock
      package: immer
      versionRange: < 9.0.6
      patchedVersion: 9.0.6
    - uri: https://github.com/scatter-ly/retail-app/security/dependabot/6
      updatedAt: 2023-04-05T17:59:31Z
      severity: high
      summary: glob-parent before 5.1.2 vulnerable to Regular Expression Denial of
        Service in enclosure regex
      manifestPath: yarn.lock
      package: glob-parent
      versionRange: < 5.1.2
      patchedVersion: 5.1.2
    - uri: https://github.com/scatter-ly/retail-app/security/dependabot/5
      updatedAt: 2023-04-05T17:59:31Z
      severity: medium
      summary: Regular Expression Denial of Service in browserslist
      manifestPath: yarn.lock
      package: browserslist
      versionRange: ">= 4.0.0, < 4.16.5"
      patchedVersion: 4.16.5
  contributors:
    - person:scatter-ly/alchen99
    - person:scatter-ly/bcornils
    - person:scatter-ly/bdwalter
---
apiVersion: opencontext.com/v1alpha1
kind: CodeComponent
metadata:
  name: retail-backend
  description: Blue Sky / Retail app backend
  title: Retail backend
  tags:
    - graphql
    - typescript
  links:
    - url: https://example.com/help
      title: Support
      icon: help
spec:
  type: repository
  owner: [person:daniel]
  dependsOn: [code-component:wholesale-graphql]
  subcomponentOf: [code-component:retail-app]
  uri: https://example.com/retail-backend
  service: retail
  lifecycle: production
  priority: 2
  sla: 8x5
