apiVersion: opencontext.com/v1alpha1
kind: CodeComponent
metadata:
  name: crates-fe
  description: Crates frontend application
  annotations:
    github.com/project-slug: 'scatter-ly/crates-frontend'
  title: Crates Frontend
  tags:
    - javascript
    - typescript
  links:
    - url: https://github.com/scatter-ly/crates-frontend/issues
      title: Issues
      icon: github
    - url: https://github.com/scatter-ly/crates-frontend/pulls
      title: Pull Requests
      icon: github
    - url: https://github.com/scatter-ly/crates-frontend/releases
      title: Releases
      icon: github
    - url: https://github.com/scatter-ly/crates-frontend/deployments
      title: Deployments
      icon: github
spec:
  type: repository
  owner: [eng-squirrel]
  platform: crates
  subcomponentOf: [code-component:crates-erp]
  uri: https://github.com/scatter-ly/crates-frontend
  languages:
    - JavaScript
    - Dockerfile
    - TypeScript
  releases: []
  contributors:
    - person:scatter-ly/alchen99
