apiVersion: 3mor.io/v1alpha1
kind: CodeComponent
metadata:
  name: crates-fe
  description: Crates frontend application
  annotations:
    github.com/project-slug: 'scatter-ly/crates-frontend'
  title: Crates Frontend
  tags:
    - javascript
    - typescript
  links:
    - url: https://github.com/scatter-ly/crates-frontend/issues
      title: Issues
      icon: github
    - url: https://github.com/scatter-ly/crates-frontend/pulls
      title: Pull Requests
      icon: github
    - url: https://github.com/scatter-ly/crates-frontend/releases
      title: Releases
      icon: github
    - url: https://github.com/scatter-ly/crates-frontend/deployments
      title: Deployments
      icon: github
spec:
  type: repository
  owner: [eng-squirrel]
  subcomponentOf: [codecomponent:crates-erp]
  service: crates
  uri: https://github.com/scatter-ly/crates-frontend
  languages:
    - JavaScript
    - Dockerfile
    - TypeScript
  vulnerabilityAlerts:
    - uri: https://github.com/scatter-ly/crates-frontend/security/dependabot/1
      updatedAt: 2023-02-07T20:33:18Z
      severity: high
      summary: Prototype Pollution in JSON5 via Parse Method
      manifestPath: yarn.lock
      package: json5
      versionRange: < 1.0.2
      patchedVersion: 1.0.2
  contributors:
    - user:scatter-ly/alchen99
