apiVersion: opencontext.com/v1alpha1
kind: CodeComponent
metadata:
  name: retail-app
  description: Blue Sky / Retail web app
  title: Retail app
  tags:
    - typescript
  links:
    - url: https://github.com/scatter-ly/retail-app/issues
      title: Issues
      icon: github
    - url: https://github.com/scatter-ly/retail-app/pulls
      title: Pull Requests
      icon: github
    - url: https://github.com/scatter-ly/retail-app/releases
      title: Releases
      icon: github
    - url: https://github.com/scatter-ly/retail-app/deployments
      title: Deployments
      icon: github
  annotations:
    github.com/project-slug: 'scatter-ly/retail-app'
spec:
  type: repository
  owner: [prod-raccoon-oss, eng-raccoon-cloud]
  dependsOn: [code-component:wholesale-graphql]
  uri: https://github.com/scatter-ly/retail-app
  languages:
    - Dockerfile
    - TypeScript
  releases:
    - name: v0.1.1
      uri: https://github.com/scatter-ly/retail-app/releases/tag/v0.1.1
    - name: v0.1.0
      uri: https://github.com/scatter-ly/retail-app/releases/tag/v0.1.0
  contributors:
    - person:scatter-ly/alchen99
---
apiVersion: opencontext.com/v1alpha1
kind: CodeComponent
metadata:
  name: retail-backend
  description: Blue Sky / Retail app backend
  title: Retail backend
  tags:
    - graphql
    - typescript
  links:
    - url: https://example.com/help
      title: Support
      icon: help
spec:
  type: repository
  owner: [person:daniel]
  dependsOn: [code-component:wholesale-graphql]
  subcomponentOf: [code-component:retail-app]
  uri: https://example.com/retail-backend
