apiVersion: opencontext.com/v1alpha1
kind: CodeComponentSidecar
metadata:
  name: retail-app-extras
spec:
  codecomponent: retail-app
  service: retail
  lifecycle: production
  priority: 2
  sla: 8x5
---
apiVersion: opencontext.com/v1alpha1
kind: CodeComponentSidecar
metadata:
  name: retail-backend-extras
spec:
  codecomponent: retail-backend
  service: retail
  lifecycle: production
  priority: 2
  sla: 8x5
---
apiVersion: opencontext.com/v1alpha1
kind: CodeComponentSidecar
metadata:
  name: wholesale-cli-extras
spec:
  codecomponent: wholesale-cli
  service: wholesale
  lifecycle: experimental
---
apiVersion: opencontext.com/v1alpha1
kind: CodeComponentSidecar
metadata:
  name: wholesale-graphql-extras
spec:
  codecomponent: wholesale-graphql
  service: wholesale
  lifecycle: experimental
