apiVersion: 3mor.io/v1alpha1
kind: CodeComponent
metadata:
  name: crates-erp
  description: Distribution Center ERP
  title: Crates ERP
  tags:
    - java
  links:
    - url: https://cybersquirrel1.com/
      title: Cyber Squirrel
      icon: dashboard
    - url: https://example.com/user
      title: Examples Users
      icon: user
    - url: https://example.com/group
      title: Example Group
      icon: group
    - url: https://example.com/cloud
      title: Link with Cloud Icon
      icon: cloud
    - url: https://example.com/dashboard
      title: Dashboard
      icon: dashboard
    - url: https://example.com/help
      title: Support
      icon: help
    - url: https://example.com/web
      title: Website
      icon: web
    - url: https://example.com/alert
      title: Alerts
      icon: alert
spec:
  type: library
  owner: [eng-squirrel]
  dependsOn: [codecomponent:greenhouse-data]
  service: crates
  uri: https://example.com/erp
  workflowsEnabled: true
