apiVersion: opencontext.com/v1alpha1
kind: CodeComponent
metadata:
  name: retail-app
  description: Blue Sky / Retail web app
  title: Retail app
  tags:
    - typescript
  links:
    - url: https://github.com/scatter-ly/retail-app/issues
      title: Issues
      icon: github
    - url: https://github.com/scatter-ly/retail-app/pulls
      title: Pull Requests
      icon: github
    - url: https://github.com/scatter-ly/retail-app/releases
      title: Releases
      icon: github
    - url: https://github.com/scatter-ly/retail-app/deployments
      title: Deployments
      icon: github
  annotations:
    github.com/project-slug: 'scatter-ly/retail-app'
spec:
  type: repository
  owner: [prod-raccoon-oss, eng-raccoon-cloud]
  dependsOn: [code-component:wholesale-graphql]
  uri: https://github.com/scatter-ly/retail-app
  languages:
    - Dockerfile
    - TypeScript
  releases:
    - name: v0.1.1
      uri: https://github.com/scatter-ly/retail-app/releases/tag/v0.1.1
    - name: v0.1.0
      uri: https://github.com/scatter-ly/retail-app/releases/tag/v0.1.0
  vulnerabilityAlerts:
    - uri: https://github.com/scatter-ly/crates-frontend/security/dependabot/1
      updatedAt: 2023-04-05T10:10:18Z
      severity: high
      summary: Prototype Pollution in JSON5 via Parse Method
      manifestPath: yarn.lock
      package: json5
      versionRange: < 1.0.2
      patchedVersion: 1.0.2
  contributors:
    - person:scatter-ly/alchen99
    - person:scatter-ly/bcornils
    - person:scatter-ly/bdwalter
---
apiVersion: opencontext.com/v1alpha1
kind: CodeComponent
metadata:
  name: retail-backend
  description: Blue Sky / Retail app backend
  title: Retail backend
  tags:
    - graphql
    - typescript
  links:
    - url: https://example.com/help
      title: Support
      icon: help
spec:
  type: repository
  owner: [person:daniel]
  dependsOn: [code-component:wholesale-graphql]
  subcomponentOf: [code-component:retail-app]
  uri: https://example.com/retail-backend
