apiVersion: 3mor.io/v1alpha1
kind: CodeComponent
metadata:
  name: dumpster-ui
  description: Dumpster frontend monorepo
  title: Dumpster UI
  tags:
    - typescript
  links:
    - url: https://github.com/scatter-ly/dumpster-ui/issues
      title: Issues
      icon: github
    - url: https://github.com/scatter-ly/dumpster-ui/pulls
      title: Pull Requests
      icon: github
    - url: https://github.com/scatter-ly/dumpster-ui/releases
      title: Releases
      icon: github
    - url: https://github.com/scatter-ly/dumpster-ui/deployments
      title: Deployments
      icon: github
  annotations:
    github.com/project-slug: 'scatter-ly/dumpster-ui'
spec:
  type: repository
  owner: [eng-raccoon-onprem, eng-raccoon-cloud, prod-raccoon-ent]
  dependsOn: [aux-component:map-thingy]
  uri: https://github.com/scatter-ly/dumpster-ui
  service: dumpster-prod
  lifecycle: production
  priority: 1
  sla: 24x7
  languages:
    - Dockerfile
    - TypeScript
  releases:
    - name: v0.1.0
      uri: https://github.com/scatter-ly/dumpster-ui/releases/tag/v0.1.0
  vulnerabilityAlerts:
    - uri: https://github.com/scatter-ly/crates-frontend/security/dependabot/1
      updatedAt: 2023-02-07T20:33:18Z
      severity: high
      summary: Prototype Pollution in JSON5 via Parse Method
      manifestPath: yarn.lock
      package: json5
      versionRange: < 1.0.2
      patchedVersion: 1.0.2
  contributors:
    - user:scatter-ly/chris-schnaidt
    - user:scatter-ly/jwithington
---
apiVersion: 3mor.io/v1alpha1
kind: CodeComponent
metadata:
  name: dumpster-map
  description: Dumpster map components
  title: Dumpster map
  tags:
    - python
  links:
    - url: https://example.com/maps
      title: Live map
      icon: website
spec:
  type: package
  owner: [eng-raccoon-onprem, eng-raccoon-cloud]
  subcomponentOf: [codecomponent:dumpster-ui]
  uri: https://example.com/map-tools
  service: dumpster-prod
---
apiVersion: 3mor.io/v1alpha1
kind: CodeComponent
metadata:
  name: d3
  description: D3 library
  title: D3
  tags:
    - javascript
    - graphs
  links:
    - url: https://example.com/examples
      title: Examples
      icon: website
spec:
  type: package
  owner: [eng-raccoon-onprem, eng-raccoon-cloud]
  subcomponentOf: [codecomponent:dumpster-ui]
  uri: https://example.com/map-tools
  service: dumpster-prod
