apiVersion: opencontext.com/v1alpha1
kind: PlatformComponent
metadata:
  name: greenhouse-lb
  description: Greenhouse load balancer
spec:
  type: loadbalancer
  subtype: external_managed
  lifecycle: production
  owner: [eng-squirrel-data]
  service: ['greenhouse']
  dependencyOf:
    ['code-component:greenhouse-mobile', code-component:greenhouse-data]
---
apiVersion: opencontext.com/v1alpha1
kind: PlatformComponent
metadata:
  name: greenhouse-db
  description: Greenhouse database
spec:
  type: database
  subtype: 'mysql 2'
  lifecycle: production
  owner: [eng-squirrel-data]
  service: ['greenhouse']
  dependsOn: ['platform-component:greenhouse-lb']
  dependencyOf: ['code-component:greenhouse-data']
  datacenter: [aws]
