apiVersion: 3mor.io/v1alpha1
kind: PlatformComponent
metadata:
  name: wholesale-lb
  description: Blue Sky / Wholesale load balancer
spec:
  type: loadbalancer
  subtype: internal
  lifecycle: experimental
  owner: [eng-raccoon-aws]
  service: [wholesale]
  dependencyOf: ['codecomponent:wholesale-cli', codecomponent:wholesale-sdk]
---
apiVersion: 3mor.io/v1alpha1
kind: PlatformComponent
metadata:
  name: wholesale-db
  description: Blue Sky / Wholesale database
spec:
  type: database
  subtype: 'postgresql 14'
  lifecycle: production
  owner: [eng-racoon-aws, it-ops, contract-crow]
  service: [wholesale]
  dependsOn: ['platform-component:wholesale-lb']
  dependencyOf: ['codecomponent:wholesale-cli']
  datacenter: [aws]
---
apiVersion: 3mor.io/v1alpha1
kind: PlatformComponent
metadata:
  name: wholesale-secrets
  description: Blue Sky / Wholesale secrets bucket
spec:
  type: s3
  subtype: private
  lifecycle: experimental
  owner: [eng-raccoon-aws]
  service: [wholesale]
  datacenter: [aws]
  dependencyOf:
    [
      platform-component:wholesale-lb,
      platform-component:wholesale-db,
      codecomponent:wholesale-cli,
    ]
  uri: s3://all-the-secrets
  priority: 2
  sla: 24x5
---
apiVersion: 3mor.io/v1alpha1
kind: PlatformComponent
metadata:
  name: wholesale-firewall
  description: Blue Sky / Wholesale firewall
spec:
  type: firewall
  lifecycle: experimental
  owner: [user:daniel]
  service: [wholesale]
  datacenter: [aws]
  dependencyOf:
    [
      platform-component:wholesale-lb,
      platform-component:wholesale-db,
      codecomponent:wholesale-sdk,
    ]
  priority: 1
  sla: 24x5
