apiVersion: opencontext.com/v1alpha1
kind: PlatformComponent
metadata:
  name: retail-vm
  description: Blue Sky / Retail virtual machine
  annotations:
    pagerduty.com/service-id: 'P2S21AB'
spec:
  type: vm
  lifecycle: production
  owner: [it-ops]
  platform: retail
  datacenter: [aws, gcp]
  dependsOn:
    ['platform-component:wholesale-lb', 'platform-component:wholesale-secrets']
  dependencyOf: ['code-component:retail-app', 'code-component:retail-backend']
  priority: 1
  sla: 24x7
---
apiVersion: opencontext.com/v1alpha1
kind: PlatformComponent
metadata:
  name: retail-dns
  description: Blue Sky / Retail DNS
  annotations:
    pagerduty.com/integration-key: 'a1be09f7001f450fd05203dceff092a2'
spec:
  type: dns
  lifecycle: production
  owner: [it-ops]
  platform: retail
  datacenter: [gcp]
  dependencyOf:
    [
      'code-component:retail-app',
      'code-component:retail-backend',
      'platform-component:wholesale-lb',
      'platform-component:wholesale-secrets',
    ]
  priority: 1
  sla: 24x7
