apiVersion: opencontext.com/v1alpha1
kind: PlatformComponent
metadata:
  name: dumpster-vm
  description: Dumpster virtual machine
  links:
    - url: https://example.com/cloud
      title: Cloud Console
      icon: cloud
    - url: https://example.com/dashboard
      title: Dumpster VM Dashboard
      icon: dashboard
  annotations:
    pagerduty.com/integration-key: '2a3703ef9af44200c024fc13c477ea48'
spec:
  type: vm
  lifecycle: production
  owner: [it-ops]
  platform: retail
  datacenter: [aws, gcp]
  dependsOn:
    [
      'platform-component:dumpster-lb',
      'platform-component:dumpster-secrets',
      'platform-component:dumpster-config',
    ]
  dependencyOf: ['code-component:dumpster-ui']
  priority: 1
  sla: 24x7
---
apiVersion: opencontext.com/v1alpha1
kind: PlatformComponent
metadata:
  name: dumpster-cloud-dns
  description: Dumpster cloud DNS
  links:
    - url: https://example.com/dns-docs
      title: DNS docs
      icon: docs
spec:
  type: dns
  lifecycle: production
  owner: [eng-raccoon]
  platform: retail
  datacenter: [aws]
  dependsOn: [platform-component:wholesale-firewall]
  dependencyOf:
    [
      'code-component:dumpster-ui',
      'platform-component:dumpster-lb',
      'platform-component:dumpster-secrets',
    ]
  priority: 1
  sla: 24x7
---
apiVersion: opencontext.com/v1alpha1
kind: PlatformComponent
metadata:
  name: dumpster-noncloud-dns
  description: Dumpster non-cloud DNS
spec:
  type: dns
  lifecycle: production
  owner: [eng-raccoon-cloud]
  platform: retail
  datacenter: [vendor]
  dependsOn: [platform-component:dumpster-db]
  dependencyOf:
    [
      'code-component:dumpster-ui',
      'platform-component:dumpster-lb',
      'platform-component:dumpster-secrets',
    ]
  priority: 1
  sla: 24x5
---
apiVersion: opencontext.com/v1alpha1
kind: PlatformComponent
metadata:
  name: dumpster-db
  description: Dumpster primary data store
  links:
    - url: https://example.com/cloud
      title: Cloud Console
      icon: cloud
    - url: https://example.com/dashboard
      title: Dumpster DB Dashboard
      icon: dashboard
  annotations:
    pagerduty.com/integration-key: '17524f4b0103460bd014c1b582c51ee7'
spec:
  type: database
  lifecycle: production
  owner: [person:daniel]
  platform: dumpster-prod
  datacenter: [aws]
  dependencyOf: [code-component:dumpster-data]
  priority: 1
  sla: 12x7
---
apiVersion: opencontext.com/v1alpha1
kind: PlatformComponent
metadata:
  name: dumpster-db-vend
  description: Dumpster vendor data store
  links:
    - url: https://example.com/vendor-docs
      title: Docs
      icon: docs
spec:
  type: database
  lifecycle: production
  owner: [person:daniel]
  platform: dumpster-prod
  datacenter: [aws]
  dependencyOf: [code-component:dumpster-data, platform-component:dumpster-db]
  priority: 1
  sla: 12x7
---
apiVersion: opencontext.com/v1alpha1
kind: PlatformComponent
metadata:
  name: dumpster-config
  description: Dumpster config bucket
  links:
    - url: https://console.cloud.google.com
      title: GCP Cloud Console
      icon: cloud
    - url: https://example.com/dumpster-config-docs
      title: Dumpster config docs
      icon: docs
  annotations:
    pagerduty.com/service-id: P7MFATB
spec:
  type: gcs
  lifecycle: production
  owner: [eng-raccoon-cloud]
  platform: crates
  datacenter: [gcp]
  dependencyOf: [platform-component:dumpster-db, code-component:dumpster-ui]
  priority: 2
  sla: 24x5
---
apiVersion: opencontext.com/v1alpha1
kind: PlatformComponent
metadata:
  name: dumpster-secrets
  description: Dumpster secrets bucket
spec:
  type: s3
  lifecycle: production
  owner: [eng-raccoon]
  platform: dumpster-prod
  datacenter: [aws]
  dependencyOf:
    [
      platform-component:dumpster-db,
      code-component:dumpster-ui,
      platform-component:retail-vm,
    ]
  uri: s3://crates-config
  priority: 3
  sla: 24x5
