apiVersion: opencontext.com/v1alpha1
kind: PlatformComponent
metadata:
  name: crates-db
  description: Crates ERP data warehouse
  links:
    - url: https://example.com/cloud
      title: Cloud Console
      icon: cloud
    - url: https://example.com/dashboard
      title: Crates DB Dashboard
      icon: dashboard
  annotations:
    pagerduty.com/integration-key: 'f7c9c5daf8414e01c0eef3e31c3bad97'
spec:
  type: database
  subtype: 'mysql 8'
  lifecycle: production
  owner: [eng-squirrel]
  service: [crates]
  datacenter: [aws]
  dependsOn: [datacenter:aws]
  dependencyOf: [code-component:crates-erp]
  priority: 2
  sla: 24x5
---
apiVersion: opencontext.com/v1alpha1
kind: PlatformComponent
metadata:
  name: crates-config
  description: Crates config bucket
  links:
    - url: https://aws.amazon.com/console
      title: AWS Cloud Console
      icon: cloud
    - url: https://example.com/crate-config-docs
      title: Crates config docs
      icon: docs
  annotations:
    pagerduty.com/service-id: PZ4K9HQ
spec:
  type: s3
  subtype: private
  lifecycle: production
  owner: [eng-squirrel]
  service: [crates]
  datacenter: [aws]
  dependencyOf: [service-component:crates-db, code-component:crates-erp]
  uri: s3://crates-config
  priority: 3
  sla: 24x5
---
apiVersion: opencontext.com/v1alpha1
kind: PlatformComponent
metadata:
  name: crates-ssl
  description: Crates SSL
  links:
    - url: https://example.com/crate-ssl-docs
      title: Crates SSL docs
      icon: docs
spec:
  type: ssl certificate
  lifecycle: production
  owner: [eng-squirrel]
  service: [crates]
  datacenter: [aws]
  dependencyOf: [platform-component:crates-db, code-component:crates-erp]
  priority: 3
  sla: 24x5
