apiVersion: opencontext.com/v1alpha1
kind: PlatformComponent
metadata:
  name: retail-vm
  description: Blue Sky / Retail virtual machine
  # annotations:
  #   pagerduty.com/integration-key: 'INTEGRATION_KEY_GOES_HERE'
spec:
  type: vm
  subtype: micro
  lifecycle: production
  owner: [it-ops]
  platform: [retail]
  datacenter: [aws, gcp]
  dependsOn:
    ['platform-component:wholesale-lb', 'platform-component:wholesale-secrets']
  dependencyOf: ['code-component:retail-app', 'code-component:retail-backend']
  priority: 1
  sla: 24x7
---
apiVersion: opencontext.com/v1alpha1
kind: PlatformComponent
metadata:
  name: retail-dns
  description: Blue Sky / Retail DNS
  # annotations:
  #   pagerduty.com/service-id: 'PAGERDUTY_SERVICE_ID'
spec:
  type: dns
  lifecycle: production
  owner: [it-ops]
  platform: [retail]
  datacenter: [gcp]
  dependencyOf:
    [
      'code-component:retail-app',
      'code-component:retail-backend',
      'platform-component:wholesale-lb',
      'platform-component:wholesale-secrets',
    ]
  priority: 1
  sla: 24x7
