apiVersion: 3mor.io/v1alpha1
kind: Platform
metadata:
  name: blue-sky
  description: Everything related to the raccoon Blue Sky Buffet project
  links:
    - url: https://buffet.example.com
      title: Project diagrams
    - url: http://example.com/platforms/orchard/dashboard
      title: Buffet Metrics Dashboard
      icon: dashboard
spec:
  owner: [team-raccoon]
