apiVersion: opencontext.com/v1alpha1
kind: Team
metadata:
  name: contract-crow
  description: Crow Contractors
spec:
  type: department
  profile:
    displayName: Crow Contractors
    email: crows@example.com
    picture: https://avatars.dicebear.com/api/identicon/crows@example.com.svg?background=%23fff&margin=25
    timezone: Australia/Melbourne
    slackHandle: crow-contractors
    pagerHandle: crow-contractors
  parent: scatterly-inc
  children: []
  members: [paul, michael]
---
apiVersion: opencontext.com/v1alpha1
kind: Person
metadata:
  name: paul
  annotations:
    'github.com/user-login': alctest-int
spec:
  ownedBy: paul
  profile:
    displayName: Paul
    displayEmail: paul@example.com
    picture: https://avatars.dicebear.com/api/avataaars/paul@example.com.svg?background=%23fff&topChance=100&eyes=default&mouth=default&top[]=shortFlat
    timezone: Australia/Perth
    slackHandle: paul
    role: Engineer
  memberOf: [contract-crow, eng-raccoon-cloud]
---
apiVersion: opencontext.com/v1alpha1
kind: Person
metadata:
  name: michael
spec:
  profile:
    displayName: Michael
    displayEmail: michael@example.com
    picture: https://avatars.dicebear.com/api/avataaars/michael@example.com.svg?background=%23fff&topChance=100&eyes=default&mouth=default&top[]=shortFlat
    timezone: Australia/Perth
    slackHandle: michael
    role: Engineer
  memberOf: [contract-crow, eng-raccoon-eco]
