apiVersion: opencontext.com/v1alpha1
kind: Team
metadata:
  name: scatterly-inc
  description: The Scatter.ly organization
  links:
    - url: http://scatter.ly/
      title: Website
    - url: https://meta.wikimedia.org/wiki/
      title: Intranet
spec:
  type: organization
  profile:
    displayName: Scatter.ly
    email: info@scatter.ly
    picture: https://avatars.dicebear.com/api/identicon/info@example.com.svg?background=%23fff&margin=25
  children: [engineering, product]
---
apiVersion: opencontext.com/v1alpha1
kind: Team
metadata:
  name: engineering
  description: Engineering Team
spec:
  type: virt-org
  profile:
    displayName: Engineering Team
    email: engineering@example.com
    picture: https://avatars.dicebear.com/api/identicon/engineering@example.com.svg?background=%23fff&margin=2
  parent: scatterly-inc
  children:
    [eng-squirrel, eng-raccoon, scatter-ly/reviewers, scatter-ly/docs-core, scatter-ly/dev-core, scatter-ly/maintainers]
---
apiVersion: opencontext.com/v1alpha1
kind: Team
metadata:
  name: product
  description: Product team
spec:
  type: virt-org
  profile:
    displayName: Product Team
    email: product@example.com
    picture: https://avatars.dicebear.com/api/identicon/product@example.com.svg?background=%23fff&margin=2
  parent: scatterly-inc
  children: [prod-squirrel, prod-raccoon]
---
apiVersion: opencontext.com/v1alpha1
kind: Location
metadata:
  name: scatterly-teams
  description: A collection of all Scatter.ly Teams
spec:
  targets:
    - ./org-crow.yaml
    - ./team-squirrel.yaml
    - ./team-raccoon.yaml
    - ./team-it-ops.yaml
    - ./eng-squirrel.yaml
    - ./eng-raccoon.yaml
    - ./prod-squirrel.yaml
    - ./prod-raccoon.yaml
    - ./scatterly-users.yaml
