apiVersion: opencontext.com/v1alpha1
kind: User
metadata:
  name: jax
  annotations:
    'github.com/user-login': alctest-dev3
spec:
  primaryEmail: jax@scatterly.com
  profile:
    displayName: Jax
    displayEmail: jax@scatterly.com
---
apiVersion: opencontext.com/v1alpha1
kind: User
metadata:
  name: fernando
  annotations:
    'github.com/user-login': alctest-dev
spec:
  primaryEmail: fernando@scatterly.com
  profile:
    displayName: Fernando
    displayEmail: fernando@scatterly.com
---
apiVersion: opencontext.com/v1alpha1
kind: User
metadata:
  name: paul
  annotations:
    'github.com/user-login': alctest-int
spec:
  primaryEmail: paul@scatterly.com
  profile:
    displayName: Paul
    displayEmail: paul@scatterly.com
