apiVersion: 3mor.io/v1alpha1
kind: AuxComponent
metadata:
  name: dumpster-map-docs
  title: Dumpster map docs
  description: Dumpster map documentation
spec:
  type: document
  lifecycle: planning
  owner: [prod-raccoon-oss]
  service: dumpster-prod
  uri: https://example.com/docsdocs
---
apiVersion: 3mor.io/v1alpha1
kind: AuxComponent
metadata:
  name: dumpster-docs
  title: Dumpster docs
  description: Dumpster project planning docs
spec:
  type: document
  lifecycle: planning
  owner: [eng-raccoon-eco]
  service: dumpster-prod
  uri: https://example.com/projdocs
---
apiVersion: 3mor.io/v1alpha1
kind: AuxComponent
metadata:
  name: dumpster-demo
  title: Dumpster demo
  description: Dumpster map demo website
spec:
  type: website
  lifecycle: planning
  owner: [eng-raccoon, prod-raccoon-oss]
  dependsOn: [codecomponent:dumpster-data]
  service: dumpster-prod
  uri: https://example.com/website
---
apiVersion: 3mor.io/v1alpha1
kind: AuxComponent
metadata:
  name: map-thingy
  title: Map thingy
  description: Prototyping toolkit for maps
spec:
  type: tool
  lifecycle: planning
  owner: [eng-raccoon-eco, prod-raccoon-ent]
  service: dumpster-prod
  uri: https://example.com/website
